### ISSUE TITLE
Cannot use examples from admin-shell-io

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-java-server-sdk#135]
Hi,

I tried to use the AAS example from admin-shell-io but I always receive errors. For example I used this one: [http://www.admin-shell-io.com/samples/aasx/15_Siemens.aasx](http://www.admin-shell-io.com/samples/aasx/15_Siemens.aasx). When I use the AAS Server from the repository from admin-shell-io then the AAS works.

KR,
BlackRose01

---

## Log From AAS Environment
```
2023-11-13 11:28:27 Loaded property file: file:application.properties
2023-11-13 11:28:27 Loaded property file: jar:file:/application/basyxExecutable.jar!/BOOT-INF/classes!/application.properties
2023-11-13 11:28:27   ____           _____              
2023-11-13 11:28:27  |  _ \         / ____|             
2023-11-13 11:28:27  | |_) |  __ _ | (___   _   _ __  __
2023-11-13 11:28:27  |  _ <  / _` | \___ \ | | | |\ \/ /
2023-11-13 11:28:27  | |_) || (_| | ____) || |_| | >  < 
2023-11-13 11:28:27  |____/  \__,_||_____/  \__, |/_/\_\
2023-11-13 11:28:27 ======================== __/ |======      
2023-11-13 11:28:27 AAS Environment         |___/                  
2023-11-13 11:28:27 2.0.0-PREVIEW
2023-11-13 11:28:27 
2023-11-13 11:28:27 2023-11-13 10:28:27.499  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Starting AasEnvironmentComponent v2.0.0-SNAPSHOT using Java 11.0.19 on 613ee99b9e69 with PID 1 (/application/basyxExecutable.jar started by nobody in /application)
2023-11-13 11:28:27 2023-11-13 10:28:27.504  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : No active profile set, falling back to 1 default profile: "default"
2023-11-13 11:28:29 2023-11-13 10:28:29.099  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2023-11-13 11:28:29 2023-11-13 10:28:29.111  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 7 ms. Found 0 MongoDB repository interfaces.
2023-11-13 11:28:29 2023-11-13 10:28:29.163  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2023-11-13 11:28:29 2023-11-13 10:28:29.180  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2023-11-13 11:28:29 2023-11-13 10:28:29.746  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2023-11-13 11:28:29 2023-11-13 10:28:29.764  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-11-13 11:28:29 2023-11-13 10:28:29.764  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.73]
2023-11-13 11:28:29 2023-11-13 10:28:29.861  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-11-13 11:28:29 2023-11-13 10:28:29.861  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2261 ms
2023-11-13 11:28:30 2023-11-13 10:28:30.138  INFO 1 --- [           main] o.e.d.b.a.c.AasRepositoryFeaturePrinter  : -------------------- Aas Repository Features: --------------------
2023-11-13 11:28:30 2023-11-13 10:28:30.138  INFO 1 --- [           main] o.e.d.b.a.c.AasRepositoryFeaturePrinter  : ----------------------------------------------------------------- 
2023-11-13 11:28:30 2023-11-13 10:28:30.141  INFO 1 --- [           main] o.e.d.b.a.c.AasServiceFeaturePrinter     : ------------------ Aas Service Found Features: ------------------ 
2023-11-13 11:28:30 2023-11-13 10:28:30.141  INFO 1 --- [           main] o.e.d.b.a.c.AasServiceFeaturePrinter     : ----------------------------------------------------------------- 
2023-11-13 11:28:30 2023-11-13 10:28:30.171  INFO 1 --- [           main] d.b.s.c.SubmodelRepositoryFeaturePrinter : -------------------- Submodel Repository Features: --------------------
2023-11-13 11:28:30 2023-11-13 10:28:30.171  INFO 1 --- [           main] d.b.s.c.SubmodelRepositoryFeaturePrinter : ----------------------------------------------------------------- 
2023-11-13 11:28:30 2023-11-13 10:28:30.173  INFO 1 --- [           main] .e.d.b.s.c.SubmodelServiceFeaturePrinter : ------------------ Submodel Service Found Features: ------------------ 
2023-11-13 11:28:30 2023-11-13 10:28:30.173  INFO 1 --- [           main] .e.d.b.s.c.SubmodelServiceFeaturePrinter : ----------------------------------------------------------------- 
2023-11-13 11:28:30 2023-11-13 10:28:30.213  INFO 1 --- [           main] nceptDescriptionRepositoryFeaturePrinter : -------------------- Concept Description Repository Features: --------------------
2023-11-13 11:28:30 2023-11-13 10:28:30.213  INFO 1 --- [           main] nceptDescriptionRepositoryFeaturePrinter : ----------------------------------------------------------------- 
2023-11-13 11:28:32 2023-11-13 10:28:32.574  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:file:/application/basyxExecutable.jar!/BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: Invocation of init method failed; nested exception is org.eclipse.digitaltwin.aas4j.v3.dataformat.DeserializationException: deserialization failed
2023-11-13 11:28:32 2023-11-13 10:28:32.577  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-11-13 11:28:32 2023-11-13 10:28:32.602  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
2023-11-13 11:28:32 
2023-11-13 11:28:32 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-11-13 11:28:32 2023-11-13 10:28:32.632 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2023-11-13 11:28:32 
2023-11-13 11:28:32 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:file:/application/basyxExecutable.jar!/BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: Invocation of init method failed; nested exception is org.eclipse.digitaltwin.aas4j.v3.dataformat.DeserializationException: deserialization failed
2023-11-13 11:28:32 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920) ~[spring-context-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.10.jar!/:2.7.10]
2023-11-13 11:28:32 at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.10.jar!/:2.7.10]
2023-11-13 11:28:32 at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.10.jar!/:2.7.10]
2023-11-13 11:28:32 at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.10.jar!/:2.7.10]
2023-11-13 11:28:32 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.10.jar!/:2.7.10]
2023-11-13 11:28:32 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.10.jar!/:2.7.10]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.basyx.aasenvironment.component.AasEnvironmentComponent.main(AasEnvironmentComponent.java:42) ~[classes!/:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2023-11-13 11:28:32 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
2023-11-13 11:28:32 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2023-11-13 11:28:32 at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
2023-11-13 11:28:32 at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 Caused by: org.eclipse.digitaltwin.aas4j.v3.dataformat.DeserializationException: deserialization failed
2023-11-13 11:28:32 at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:101) ~[dataformat-xml-1.0.0-milestone-03.1.jar!/:na]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.aas4j.v3.dataformat.aasx.AASXDeserializer.read(AASXDeserializer.java:94) ~[dataformat-aasx-1.0.0-milestone-03.1.jar!/:na]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.getEnvironmentFromFile(AasEnvironmentPreconfigurationLoader.java:155) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.loadPreconfiguredEnvironment(AasEnvironmentPreconfigurationLoader.java:81) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.loadPreconfiguredEnvironment(PreconfigurationLoaderInitializer.java:76) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.afterPropertiesSet(PreconfigurationLoaderInitializer.java:68) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.26.jar!/:5.3.26]
2023-11-13 11:28:32 ... 24 common frames omitted
2023-11-13 11:28:32 Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultEnvironment["submodels"]->java.util.ArrayList[0]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodel["semanticId"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultReference["keys"])
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1821) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91) ~[jackson-dataformat-xml-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:99) ~[dataformat-xml-1.0.0-milestone-03.1.jar!/:na]
2023-11-13 11:28:32 ... 31 common frames omitted
2023-11-13 11:28:32 Caused by: java.lang.NullPointerException: null
2023-11-13 11:28:32 at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.KeyDeserializer.readValue(KeyDeserializer.java:35) ~[dataformat-xml-1.0.0-milestone-03.1.jar!/:na]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.KeyDeserializer.readValue(KeyDeserializer.java:27) ~[dataformat-xml-1.0.0-milestone-03.1.jar!/:na]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.NoEntryWrapperListDeserializer.createEntriesFromObjectNode(NoEntryWrapperListDeserializer.java:66) ~[dataformat-xml-1.0.0-milestone-03.1.jar!/:na]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.NoEntryWrapperListDeserializer.deserialize(NoEntryWrapperListDeserializer.java:50) ~[dataformat-xml-1.0.0-milestone-03.1.jar!/:na]
2023-11-13 11:28:32 at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.NoEntryWrapperListDeserializer.deserialize(NoEntryWrapperListDeserializer.java:36) ~[dataformat-xml-1.0.0-milestone-03.1.jar!/:na]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[jackson-databind-2.13.5.jar!/:2.13.5]
2023-11-13 11:28:32 ... 46 common frames omitted
```

**Comment by FrankSchnicke** [comment]
Hi, the examples provided there are all meta model version 2. 

The components developed in _basyx-java-server-sdk_ (i.e., BaSyx Version 2) are all focusing on meta model version 3. For meta model version 2, take a look at the existing components of BaSyx Version 1:
https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components

**Comment by BlackRose01** [comment]
Is downward compatibility planned?

**Comment by FrankSchnicke** [comment]
We are considering downwards compatibility but it is not on our immediate roadmap as of today. The AASX Package Explorer is offering a conversion - however, it currently has some compatibility issues (cf. https://github.com/eclipse-aas4j/aas4j/issues/158)

**Comment by BlackRose01** [comment]
Ok. I tried the conversion of the AASX with the Package Explorer and it doesn't work for me. The error from the examples could not be fixed. But it would be very nice to use older meta models with the server.
