### ISSUE TITLE
Error when loading an AASX version 3 designed by AASX Package Explorer

### ISSUE THREAD

**Issue by stolze-ifak** [eclipse-basyx/basyx-java-server-sdk#152]
I tried to uplad an AASX file, that I created with the newest version of the AASX Package Explorer. But the docker exited with following message:

```
 aas-env-setup-aas-environment-1  | Loaded property file: file:application.properties
aas-env-setup-aas-environment-1  | Loaded property file: jar:file:/application/basyxExecutable.jar!/BOOT-INF/classes!/application.properties
aas-env-setup-aas-environment-1  |   ____           _____
aas-env-setup-aas-environment-1  |  |  _ \         / ____|
aas-env-setup-aas-environment-1  |  | |_) |  __ _ | (___   _   _ __  __
aas-env-setup-aas-environment-1  |  |  _ <  / _` | \___ \ | | | |\ \/ /
aas-env-setup-aas-environment-1  |  | |_) || (_| | ____) || |_| | >  < 
aas-env-setup-aas-environment-1  |  |____/  \__,_||_____/  \__, |/_/\_\
aas-env-setup-aas-environment-1  | ======================== __/ |======
aas-env-setup-aas-environment-1  | AAS Environment         |___/
aas-env-setup-aas-environment-1  | 2.0.0-PREVIEW
aas-env-setup-aas-environment-1  | 
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:49.283  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Starting AasEnvironmentComponent v2.0.0-SNAPSHOT using Java 11.0.19 on 41191ef49191 with PID 1 (/application/basyxExecutable.jar started by nobody in /application)
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:49.285  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : No active profile set, falling back to 1 default profile: "default"
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:50.423  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:50.433  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 5 ms. Found 0 MongoDB repository interfaces.
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:50.493  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:50.507  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:50.949  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:50.963  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:50.964  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.73]
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:51.045  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:51.045  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1691 ms
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:52.300  WARN 1 --- [           main] o.e.d.a.v.d.aasx.AASXDeserializer        : AASX contains wrong Relationship namespace. This may be related to a bug in AASX Package Explorer or an old version of AAS4J. Future compatibility with the wrong namespace may not be guaranteed
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:52.507  WARN 1 --- [           main] o.e.d.a.v.d.aasx.AASXDeserializer        : AASX contains wrong Relationship namespace. This may be related to a bug in AASX Package Explorer or an old version of AAS4J. Future compatibility with the wrong namespace may not be guaranteed
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:52.529  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating 
bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:file:/application/basyxExecutable.jar!/BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: Invocation of init method failed; nested exception is org.eclipse.digitaltwin.aas4j.v3.dataformat.DeserializationException: deserialization failed
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:52.533  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:52.552  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
aas-env-setup-aas-environment-1  | 
aas-env-setup-aas-environment-1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
aas-env-setup-aas-environment-1  | 2023-12-01 11:55:52.577 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
aas-env-setup-aas-environment-1  | 
aas-env-setup-aas-environment-1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:file:/application/basyxExecutable.jar!/BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: Invocation of init method failed; nested exception is org.eclipse.digitaltwin.aas4j.v3.dataformat.DeserializationException: deserialization failed
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) 
~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920) ~[spring-context-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.10.jar!/:2.7.10]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.10.jar!/:2.7.10]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.10.jar!/:2.7.10]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.10.jar!/:2.7.10]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.10.jar!/:2.7.10]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.10.jar!/:2.7.10]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.basyx.aasenvironment.component.AasEnvironmentComponent.main(AasEnvironmentComponent.java:42) ~[classes!/:2.0.0-SNAPSHOT]
aas-env-setup-aas-environment-1  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
aas-env-setup-aas-environment-1  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
aas-env-setup-aas-environment-1  |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
aas-env-setup-aas-environment-1  |      at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
aas-env-setup-aas-environment-1  |      at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
aas-env-setup-aas-environment-1  | Caused by: org.eclipse.digitaltwin.aas4j.v3.dataformat.DeserializationException: deserialization failed     
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:119) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.aasx.AASXDeserializer.read(AASXDeserializer.java:100) ~[dataformat-aasx-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.getEnvironmentFromFile(AasEnvironmentPreconfigurationLoader.java:155) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.loadPreconfiguredEnvironment(AasEnvironmentPreconfigurationLoader.java:81) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]     
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.loadPreconfiguredEnvironment(PreconfigurationLoaderInitializer.java:76) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.afterPropertiesSet(PreconfigurationLoaderInitializer.java:68) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.26.jar!/:5.3.26]
aas-env-setup-aas-environment-1  |      ... 24 common frames omitted
aas-env-setup-aas-environment-1  | Caused by: com.fasterxml.jackson.databind.JsonMappingException: class com.fasterxml.jackson.databind.node.TextNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.TextNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @61a485d2) (through reference chain: org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultEnvironment["submodels"]->java.util.ArrayList[0]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodel["submodelElements"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultProperty["qualifiers"])
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1821) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316) 
~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91) ~[jackson-dataformat-xml-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2277) ~[jackson-core-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.DeserializationHelper.createInstanceFromNode(DeserializationHelper.java:32) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.SubmodelElementDeserializer.deserialize(SubmodelElementDeserializer.java:37) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.SubmodelElementsDeserializer.getSubmodelElementFromJsonNode(SubmodelElementsDeserializer.java:103) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.SubmodelElementsDeserializer.getSubmodelElementsFromObjectNode(SubmodelElementsDeserializer.java:80) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.SubmodelElementsDeserializer.createSubmodelElements(SubmodelElementsDeserializer.java:61) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:53) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:36) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) 
~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) 
~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) 
~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) 
~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91) ~[jackson-dataformat-xml-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597) ~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:117) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      ... 31 common frames omitted
aas-env-setup-aas-environment-1  | Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.TextNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.TextNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @61a485d2)
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.DeserializationHelper.getRootObjectNode(DeserializationHelper.java:50) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.QualifierDeserializer.deserialize(QualifierDeserializer.java:62) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.deserialization.QualifierDeserializer.deserialize(QualifierDeserializer.java:58) ~[dataformat-xml-1.0.0-milestone-04.jar!/:na]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) 
~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) 
~[jackson-databind-2.13.5.jar!/:2.13.5]
aas-env-setup-aas-environment-1  |      ... 57 common frames omitted
aas-env-setup-aas-environment-1  |
aas-env-setup-aas-environment-1 exited with code 1
```

Then I saved the AAS in json format and this works with some warnings. The following messages occured:

```
aas-env-setup-aas-environment-1  | Loaded property file: file:application.properties
aas-env-setup-aas-environment-1  | Loaded property file: jar:file:/application/basyxExecutable.jar!/BOOT-INF/classes!/application.properties
aas-env-setup-aas-environment-1  |   ____           _____
aas-env-setup-aas-environment-1  |  |  _ \         / ____|
aas-env-setup-aas-environment-1  |  | |_) |  __ _ | (___   _   _ __  __
aas-env-setup-aas-environment-1  |  |  _ <  / _` | \___ \ | | | |\ \/ /
aas-env-setup-aas-environment-1  |  | |_) || (_| | ____) || |_| | >  < 
aas-env-setup-aas-environment-1  |  |____/  \__,_||_____/  \__, |/_/\_\
aas-env-setup-aas-environment-1  | ======================== __/ |======
aas-env-setup-aas-environment-1  | AAS Environment         |___/
aas-env-setup-aas-environment-1  | 2.0.0-PREVIEW
aas-env-setup-aas-environment-1  | 
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:27.069  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Starting AasEnvironmentComponent v2.0.0-SNAPSHOT using Java 11.0.19 on 41191ef49191 with PID 1 (/application/basyxExecutable.jar started by nobody in /application)
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:27.071  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : No active profile set, falling back to 1 default profile: "default"
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.261  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.271  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 6 ms. Found 0 MongoDB repository interfaces.
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.327  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.344  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.788  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.802  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.802  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.73]
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.884  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:28.884  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1756 ms
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.098  WARN 1 --- [           main] o.e.d.a.v.d.aasx.AASXDeserializer        : AASX contains wrong Relationship namespace. This may be related to a bug in AASX Package Explorer or an old version of AAS4J. Future compatibility with the wrong namespace may not be guaranteed
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.459  INFO 1 --- [           main] o.e.d.b.a.c.AasRepositoryFeaturePrinter  : -------------------- Aas Repository Features: --------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.459  INFO 1 --- [           main] o.e.d.b.a.c.AasRepositoryFeaturePrinter  : -----------------------------------------------------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.460  INFO 1 --- [           main] o.e.d.b.a.c.AasServiceFeaturePrinter     : ------------------ Aas Service Found Features: ------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.460  INFO 1 --- [           main] o.e.d.b.a.c.AasServiceFeaturePrinter     : -----------------------------------------------------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.461  INFO 1 --- [           main] d.b.s.c.SubmodelRepositoryFeaturePrinter : -------------------- Submodel Repository Features: --------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.461  INFO 1 --- [           main] d.b.s.c.SubmodelRepositoryFeaturePrinter : -----------------------------------------------------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.462  INFO 1 --- [           main] .e.d.b.s.c.SubmodelServiceFeaturePrinter : ------------------ Submodel Service Found Features: ------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.462  INFO 1 --- [           main] .e.d.b.s.c.SubmodelServiceFeaturePrinter : -----------------------------------------------------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.465  INFO 1 --- [           main] nceptDescriptionRepositoryFeaturePrinter : -------------------- Concept Description Repository Features: --------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:30.465  INFO 1 --- [           main] nceptDescriptionRepositoryFeaturePrinter : -----------------------------------------------------------------
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:31.298  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 
endpoint(s) beneath base path '/actuator'
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:31.418  INFO 1 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:31.418  INFO 1 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'AAS Environment.errorChannel' has 1 subscriber(s).
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:31.418  INFO 1 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:31.441  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
aas-env-setup-aas-environment-1  | 2023-12-01 11:58:31.460  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Started AasEnvironmentComponent in 4.854 seconds (JVM running for 5.301)
``` 

To reproduce the problem use:

[AASX-Package Explorer Version v2023-11-17](https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2023-11-17.alpha)
[aas-env-setup.zip](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/13526301/aas-env-setup.zip) (In the zip-file both AAS formats are saved in /aas.)

**Comment by FrankSchnicke** [comment]
This is relatedto the AASX Package Explorer producing XML files that contain empty entries which is not in line with the official XML specification. They are aware of this issue but I'm not sure about their timeline on fixing this.
