### ISSUE TITLE
Failed to register Submodel Descriptor without embeddedDataSpecifications

### ISSUE THREAD

**Issue by oalagtash** [eclipse-basyx/basyx-java-server-sdk#187]
When I send a post request to submodel registry I get a 400 BAD_REQUEST with following error response:
```
Caused by: org.eclipse.digitaltwin.basyx.submodelregistry.client.ApiException: postSubmodelDescriptor call failed with: 400 - {"messages":[{"code":"Bad Request","messageType":"Exception","text":"Field error in object 'submodelDescriptor' on field 'administration.embeddedDataSpecifications[0].dataSpecificationContent': rejected value [null]; codes [NotNull.submodelDescriptor.administration.embeddedDataSpecifications[0].dataSpecificationContent,NotNull.submodelDescriptor.administration.embeddedDataSpecifications.dataSpecificationContent,NotNull.administration.embeddedDataSpecifications[0].dataSpecificationContent,NotNull.administration.embeddedDataSpecifications.dataSpecificationContent,NotNull.dataSpecificationContent,NotNull.org.eclipse.digitaltwin.basyx.submodelregistry.model.DataSpecificationContent,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [submodelDescriptor.administration.embeddedDataSpecifications[0].dataSpecificationContent,administration.embeddedDataSpecifications[0].dataSpecificationContent]; arguments []; default message [administration.embeddedDataSpecifications[0].dataSpecificationContent]]; default message [must not be null]","timestamp":"2024-01-24T10:29:53.142484+01:00"}]}
	at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.getApiException(SubmodelRegistryApi.java:102)
	at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.postSubmodelDescriptorWithHttpInfo(SubmodelRegistryApi.java:520)
	at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.postSubmodelDescriptor(SubmodelRegistryApi.java:498)

``` 

The API enforces to set `org.eclipse.digitaltwin.basyx.submodelregistry.model.AdministrativeInformation#embeddedDataSpecifications`, which in some cases is not need. 
This field is validated with `@Valid` annotation:
```
  @Valid
  private List<@Valid EmbeddedDataSpecification> embeddedDataSpecifications;
```

Furthermore, setting this field does not make it valid. There is something wrong in the validation settings itself.

Let me know if you need more info. :)

Many thanks for looking into it!

**Comment by geso02** [comment]
Based on the error message path (administration.embeddedDataSpecifications[0].dataSpecificationContent) I assume that the dataspecification has no dataSpecificationContent attribute set. According to the OpenAPI description, this is a required property:  https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/EmbeddedDataSpecification

Could you please verify that the content is set or provide a snippet of your data specification structure?

**Comment by oalagtash** [comment]
While it is true that the exception I provided was misleading, the main issue I have is creating an `AdministrativeInformation` for a `SubmodelDescriptor` without defining `EmbeddedDataSpecifications`.  Here is the actual exception I meant to provide:
```
Caused by: org.eclipse.digitaltwin.basyx.submodelregistry.client.ApiException: postSubmodelDescriptor call failed with: 400 - {"messages":[{"code":"Bad Request","messageType":"Exception","text":"Field error in object 'submodelDescriptor' on field 'administration.embeddedDataSpecifications': rejected value [[]]; codes [Size.submodelDescriptor.administration.embeddedDataSpecifications,Size.administration.embeddedDataSpecifications,Size.embeddedDataSpecifications,Size.java.util.List,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [submodelDescriptor.administration.embeddedDataSpecifications,administration.embeddedDataSpecifications]; arguments []; default message [administration.embeddedDataSpecifications],2147483647,1]; default message [size must be between 1 and 2147483647]","timestamp":"2024-01-25T09:39:04.80137601Z"}]}
	at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.getApiException(SubmodelRegistryApi.java:102)
	at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.postSubmodelDescriptorWithHttpInfo(SubmodelRegistryApi.java:520)
	at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.postSubmodelDescriptor(SubmodelRegistryApi.java:498)
```

**Comment by geso02** [comment]
The size of the embeddedDataSpecifications array needs to be at least 1

https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/AdministrativeInformation

Seems to be an empty array in your case.

**Comment by FrankSchnicke** [comment]
@oalagtash is this still active or did @geso02 comment solve your issue?
