### ISSUE TITLE
Error on starting AAS

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-java-server-sdk#276]
Hi,

for testing purposes I recently created a new AAS with the Package Explorer, which does not contain much data. This is to be rolled out via Docker and registered with a registry. Unfortunately, I always get the error `Caused by: org.eclipse.digitaltwin.basyx.aasregistry.client.ApiException: postAssetAdministrationShellDescriptor call failed with: 404 - 404 page not found` when I start my AAS for the first time. If I start the AAS Environment 2-3 times, the loading works afterwards without any problems. Unfortunately, I have been able to reproduce this with other AASs, but cannot identify the error myself.

I also attached the AAS Docker setup.

KR,
BlackRose01

[aas.zip](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15188696/aas.zip)

## Setup
Plattform: Docker on Ubuntu 22.04.01
AAS Package Explorer Version: v2024-03-05
Registry Version: aas-registry-log-mem:2.0.0-SNAPSHOT
AAS Version: aas-environment:2.0.0-SNAPSHOT

### Log with error
```log
Loaded property file: file:application.properties
Loaded property file: jar:file:/application/basyxExecutable.jar!/BOOT-INF/classes!/application.properties
  ____           _____
 |  _ \         / ____|
 | |_) |  __ _ | (___   _   _ __  __
 |  _ <  / _` | \___ \ | | | |\ \/ /
 | |_) || (_| | ____) || |_| | >  <
 |____/  \__,_||_____/  \__, |/_/\_\
======================== __/ |======
AAS Environment         |___/
2.0.0-PREVIEW

2024-05-02T12:39:22.615Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Starting AasEnvironmentComponent v2.0.0-SNAPSHOT using Java 17.0.10 with PID 1 (/application/basyxExecutable.jar started by nobody in /application)
2024-05-02T12:39:22.618Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : No active profile set, falling back to 1 default profile: "default"
2024-05-02T12:39:24.890Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2024-05-02T12:39:24.905Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11 ms. Found 0 MongoDB repository interfaces.
2024-05-02T12:39:24.968Z  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2024-05-02T12:39:24.990Z  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2024-05-02T12:39:25.744Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2024-05-02T12:39:25.757Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-05-02T12:39:25.758Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.13]
2024-05-02T12:39:25.860Z  INFO 1 --- [           main] o.a.c.c.C.[.[localhost].[/api/v3.0]      : Initializing Spring embedded WebApplicationContext
2024-05-02T12:39:25.861Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3169 ms
2024-05-02T12:39:26.124Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentFeaturePrinter : -------------------- Aas Environment Features: --------------------
2024-05-02T12:39:26.124Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentFeaturePrinter : -----------------------------------------------------------------
2024-05-02T12:39:27.921Z  INFO 1 --- [           main] a.p.AasEnvironmentPreconfigurationLoader : Scanning for preconfigured AAS Environments
2024-05-02T12:39:27.932Z  INFO 1 --- [           main] a.p.AasEnvironmentPreconfigurationLoader : Found 1 preconfigured AAS environments
2024-05-02T12:39:27.933Z  INFO 1 --- [           main] a.p.AasEnvironmentPreconfigurationLoader : Loading AAS Environment (0/1) from file 'aas.aasx'
2024-05-02T12:39:28.067Z  INFO 1 --- [           main] o.e.d.a.v.d.aasx.AASXDeserializer        : AASX contains wrong Relationship namespace. This may be related to the AASX being created with an old version of AASX Package Explorer or an old version of AAS4J. Future compatibility with the wrong namespace may not be guaranteed
2024-05-02T12:39:28.300Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:28.322Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:28.322Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:28.323Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:28.323Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:28.324Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:28.481Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:file:/application/basyxExecutable.jar!/BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: Unable to link the element with id 'https://example.com/ids/sm/3511_2103_4042_5368' with the Registry.
2024-05-02T12:39:28.484Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-05-02T12:39:28.509Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-05-02T12:39:28.534Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:file:/application/basyxExecutable.jar!/BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: Unable to link the element with id 'https://example.com/ids/sm/3511_2103_4042_5368' with the Registry.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[spring-context-6.0.12.jar!/:6.0.12]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.12.jar!/:6.0.12]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.4.jar!/:3.1.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[spring-boot-3.1.4.jar!/:3.1.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.1.4.jar!/:3.1.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-3.1.4.jar!/:3.1.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-3.1.4.jar!/:3.1.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-3.1.4.jar!/:3.1.4]
        at org.eclipse.digitaltwin.basyx.aasenvironment.component.AasEnvironmentComponent.main(AasEnvironmentComponent.java:42) ~[classes!/:2.0.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
Caused by: org.eclipse.digitaltwin.basyx.core.exceptions.RepositoryRegistryLinkException: Unable to link the element with id 'https://example.com/ids/sm/3511_2103_4042_5368' with the Registry.
        at org.eclipse.digitaltwin.basyx.aasrepository.feature.registry.integration.RegistryIntegrationAasRepository.integrateAasWithRegistry(RegistryIntegrationAasRepository.java:137) ~[basyx.aasrepository-feature-registry-integration-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasrepository.feature.registry.integration.RegistryIntegrationAasRepository.createAas(RegistryIntegrationAasRepository.java:82) ~[basyx.aasrepository-feature-registry-integration-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasenvironment.environmentloader.IdentifiableUploader$DelegatingIdentifiableRepository.create(IdentifiableUploader.java:158) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasenvironment.environmentloader.IdentifiableUploader.create(IdentifiableUploader.java:94) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasenvironment.environmentloader.IdentifiableUploader.upload(IdentifiableUploader.java:55) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasenvironment.base.DefaultAASEnvironment.createShellsOnRepositoryFromEnvironment(DefaultAASEnvironment.java:188) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasenvironment.base.DefaultAASEnvironment.loadEnvironment(DefaultAASEnvironment.java:124) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.loadPreconfiguredEnvironments(AasEnvironmentPreconfigurationLoader.java:85) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.loadPreconfiguredEnvironment(PreconfigurationLoaderInitializer.java:68) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.afterPropertiesSet(PreconfigurationLoaderInitializer.java:60) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817) ~[spring-beans-6.0.12.jar!/:6.0.12]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[spring-beans-6.0.12.jar!/:6.0.12]
        ... 24 common frames omitted
Caused by: org.eclipse.digitaltwin.basyx.aasregistry.client.ApiException: postAssetAdministrationShellDescriptor call failed with: 404 - 404 page not found

        at org.eclipse.digitaltwin.basyx.aasregistry.client.api.RegistryAndDiscoveryInterfaceApi.getApiException(RegistryAndDiscoveryInterfaceApi.java:107) ~[basyx.aasregistry-client-native-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasregistry.client.api.RegistryAndDiscoveryInterfaceApi.postAssetAdministrationShellDescriptorWithHttpInfo(RegistryAndDiscoveryInterfaceApi.java:799) ~[basyx.aasregistry-client-native-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasregistry.client.api.RegistryAndDiscoveryInterfaceApi.postAssetAdministrationShellDescriptor(RegistryAndDiscoveryInterfaceApi.java:777) ~[basyx.aasregistry-client-native-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at org.eclipse.digitaltwin.basyx.aasrepository.feature.registry.integration.RegistryIntegrationAasRepository.integrateAasWithRegistry(RegistryIntegrationAasRepository.java:133) ~[basyx.aasrepository-feature-registry-integration-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        ... 35 common frames omitted
```

## Log success
```log
Loaded property file: file:application.properties
Loaded property file: jar:file:/application/basyxExecutable.jar!/BOOT-INF/classes!/application.properties
  ____           _____
 |  _ \         / ____|
 | |_) |  __ _ | (___   _   _ __  __
 |  _ <  / _` | \___ \ | | | |\ \/ /
 | |_) || (_| | ____) || |_| | >  <
 |____/  \__,_||_____/  \__, |/_/\_\
======================== __/ |======
AAS Environment         |___/
2.0.0-PREVIEW

2024-05-02T12:39:33.763Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Starting AasEnvironmentComponent v2.0.0-SNAPSHOT using Java 17.0.10 with PID 1 (/application/basyxExecutable.jar started by nobody in /application)
2024-05-02T12:39:33.766Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : No active profile set, falling back to 1 default profile: "default"
2024-05-02T12:39:35.992Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2024-05-02T12:39:36.008Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11 ms. Found 0 MongoDB repository interfaces.
2024-05-02T12:39:36.068Z  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2024-05-02T12:39:36.087Z  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2024-05-02T12:39:36.752Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2024-05-02T12:39:36.764Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-05-02T12:39:36.765Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.13]
2024-05-02T12:39:36.858Z  INFO 1 --- [           main] o.a.c.c.C.[.[localhost].[/api/v3.0]      : Initializing Spring embedded WebApplicationContext
2024-05-02T12:39:36.860Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3020 ms
2024-05-02T12:39:37.113Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentFeaturePrinter : -------------------- Aas Environment Features: --------------------
2024-05-02T12:39:37.113Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentFeaturePrinter : -----------------------------------------------------------------
2024-05-02T12:39:39.008Z  INFO 1 --- [           main] a.p.AasEnvironmentPreconfigurationLoader : Scanning for preconfigured AAS Environments
2024-05-02T12:39:39.020Z  INFO 1 --- [           main] a.p.AasEnvironmentPreconfigurationLoader : Found 1 preconfigured AAS environments
2024-05-02T12:39:39.020Z  INFO 1 --- [           main] a.p.AasEnvironmentPreconfigurationLoader : Loading AAS Environment (0/1) from file 'aas.aasx'
2024-05-02T12:39:39.159Z  INFO 1 --- [           main] o.e.d.a.v.d.aasx.AASXDeserializer        : AASX contains wrong Relationship namespace. This may be related to the AASX being created with an old version of AASX Package Explorer or an old version of AAS4J. Future compatibility with the wrong namespace may not be guaranteed
2024-05-02T12:39:39.402Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:39.447Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:39.448Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:39.448Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:39.448Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:39.450Z  INFO 1 --- [           main] v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
2024-05-02T12:39:39.937Z  INFO 1 --- [           main] a.f.r.i.RegistryIntegrationAasRepository : Shell 'https://example.com/ids/sm/3511_2103_4042_5368' has been automatically linked with the Registry
2024-05-02T12:39:39.937Z  INFO 1 --- [           main] o.e.d.b.a.base.DefaultAASEnvironment     : Uploading shell https://example.com/ids/sm/3511_2103_4042_5368 was successful!
2024-05-02T12:39:39.938Z  INFO 1 --- [           main] o.e.d.b.a.base.DefaultAASEnvironment     : Uploading submodel https://example.com/ids/sm/1332_1103_4042_4311 was successful!
2024-05-02T12:39:39.938Z  INFO 1 --- [           main] o.e.d.b.a.base.DefaultAASEnvironment     : Uploading submodel https://example.com/ids/sm/5403_1103_4042_6786 was successful!
2024-05-02T12:39:39.938Z  INFO 1 --- [           main] o.e.d.b.a.base.DefaultAASEnvironment     : Uploading submodel https://example.com/ids/sm/3511_2103_4042_8368 was successful!
2024-05-02T12:39:39.941Z  INFO 1 --- [           main] o.e.d.b.a.c.AasRepositoryFeaturePrinter  : -------------------- Aas Repository Features: --------------------
2024-05-02T12:39:39.941Z  INFO 1 --- [           main] o.e.d.b.a.c.AasRepositoryFeaturePrinter  : BaSyxFeature AasRepository Registry Integration is enabled: true
2024-05-02T12:39:39.941Z  INFO 1 --- [           main] o.e.d.b.a.c.AasRepositoryFeaturePrinter  : -----------------------------------------------------------------
2024-05-02T12:39:39.942Z  INFO 1 --- [           main] o.e.d.b.a.c.AasServiceFeaturePrinter     : ------------------ Aas Service Found Features: ------------------
2024-05-02T12:39:39.942Z  INFO 1 --- [           main] o.e.d.b.a.c.AasServiceFeaturePrinter     : -----------------------------------------------------------------
2024-05-02T12:39:39.943Z  INFO 1 --- [           main] d.b.s.c.SubmodelRepositoryFeaturePrinter : -------------------- Submodel Repository Features: --------------------
2024-05-02T12:39:39.943Z  INFO 1 --- [           main] d.b.s.c.SubmodelRepositoryFeaturePrinter : BaSyxFeature SubmodelRepository Operation Delegation is enabled: true
2024-05-02T12:39:39.943Z  INFO 1 --- [           main] d.b.s.c.SubmodelRepositoryFeaturePrinter : -----------------------------------------------------------------
2024-05-02T12:39:39.944Z  INFO 1 --- [           main] .e.d.b.s.c.SubmodelServiceFeaturePrinter : ------------------ Submodel Service Found Features: ------------------
2024-05-02T12:39:39.944Z  INFO 1 --- [           main] .e.d.b.s.c.SubmodelServiceFeaturePrinter : -----------------------------------------------------------------
2024-05-02T12:39:39.946Z  INFO 1 --- [           main] nceptDescriptionRepositoryFeaturePrinter : -------------------- Concept Description Repository Features: --------------------
2024-05-02T12:39:39.946Z  INFO 1 --- [           main] nceptDescriptionRepositoryFeaturePrinter : -----------------------------------------------------------------
2024-05-02T12:39:40.483Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : ---- Configuring CORS ----
2024-05-02T12:39:40.483Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /shells/** configured with allowedOriginPatterns [*]
2024-05-02T12:39:40.483Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /shells/** configured with allowedMethods [GET, POST, PATCH, DELETE, PUT, OPTIONS, HEAD]
2024-05-02T12:39:40.485Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /submodels/** configured with allowedOriginPatterns [*]
2024-05-02T12:39:40.485Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /submodels/** configured with allowedMethods [GET, POST, PATCH, DELETE, PUT, OPTIONS, HEAD]
2024-05-02T12:39:40.485Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /concept-descriptions/** configured with allowedOriginPatterns [*]
2024-05-02T12:39:40.485Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /concept-descriptions/** configured with allowedMethods [GET, POST, PATCH, DELETE, PUT, OPTIONS, HEAD]
2024-05-02T12:39:40.485Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /serialization configured with allowedOriginPatterns [*]
2024-05-02T12:39:40.485Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /serialization configured with allowedMethods [GET, POST, PATCH, DELETE, PUT, OPTIONS, HEAD]
2024-05-02T12:39:40.485Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /upload configured with allowedOriginPatterns [*]
2024-05-02T12:39:40.486Z  INFO 1 --- [           main] o.e.d.basyx.http.BaSyxHTTPConfiguration  : /upload configured with allowedMethods [GET, POST, PATCH, DELETE, PUT, OPTIONS, HEAD]
2024-05-02T12:39:40.892Z  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2024-05-02T12:39:41.024Z  INFO 1 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2024-05-02T12:39:41.025Z  INFO 1 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'AAS Environment.errorChannel' has 1 subscriber(s).
2024-05-02T12:39:41.025Z  INFO 1 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2024-05-02T12:39:41.038Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path '/api/v3.0'
2024-05-02T12:39:41.059Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Started AasEnvironmentComponent in 7.825 seconds (process running for 8.488)
2024-05-02T12:39:51.181Z  INFO 1 --- [nio-8081-exec-1] o.a.c.c.C.[.[localhost].[/api/v3.0]      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-05-02T12:39:51.182Z  INFO 1 --- [nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-05-02T12:39:51.183Z  INFO 1 --- [nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
```

**Comment by mdanish98** [comment]
Hi @BlackRose01 ,

Thanks for raising this issue.
Could you please also share the application.properties?

**Comment by BlackRose01** [comment]
The application.properties is the aas-env.properties file.

**Comment by mdanish98** [comment]
We will take a look and get back to you.

**Comment by FriedJannik** [comment]
Hi @BlackRose01,
there were two issues with the configuration provided:
1 - the aas-environment container did not wait, until the registry container is healthy, it just waited for it to be started
2 - the registry endpoint URL was not pointing to the registry endpoint

I added a health check condition to the docker compose file, a hostname for the registry container and adapted the endpoint URL.

Please try the attached configuration, it should work with these:
[aas_env.zip](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15304113/aas_env.zip)
