### ISSUE TITLE
[BUG] Keycloak does not run in virtual machine

### ISSUE THREAD

**Issue by gerberm-at-msg** [eclipse-basyx/basyx-java-server-sdk#387]
**Describe the bug**
I can run the "image: eclipsebasyx/keycloak:0.0.1" on linux with an intel cpu. However, if I let it run at an M3-Chip it fails with the following error message. I tried to add the manifest manually, but it probably needs to be provided in the docker file itself. 

```
 => [keycloak internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 654B                                                                                                                             0.0s
 => [keycloak] resolve image config for docker-image://docker.io/docker/dockerfile:1                                                                             0.9s
 => CACHED [keycloak] docker-image://docker.io/docker/dockerfile:1@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28                       0.0s
 => CANCELED [keycloak internal] load metadata for docker.io/keycloak/keycloak:24.0.4                                                                            0.7s
 => ERROR [keycloak internal] load metadata for docker.io/library/maven:3-eclipse-temurin-17-alpine                                                              0.7s
------
 > [keycloak internal] load metadata for docker.io/library/maven:3-eclipse-temurin-17-alpine:
------
failed to solve: maven:3-eclipse-temurin-17-alpine: no match for platform in manifest: not found
```

**To Reproduce**
Run the rbac-example on a M3-Mac (I have a debian-vm in between).

**Expected behavior**
It would normally start

**BaSyx (please complete the following information):**
- BaSyx Version 2.0.0-milestone-03.1
- BaSyx SDK 
- AAS Version V3

**BaSyx configuration**
```  keycloak:
    image: eclipsebasyx/keycloak:0.0.1
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak-rbac
    environment:
      KC_HOSTNAME: keycloak-rbac
      KC_SPI_INITIALIZER_ISSUER_BASE_URI: http://192.168.178.75:8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak-admin
    command: ["start-dev", "--import-realm"]
    ports:
      - 9097:8080
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
```
**System (please complete the following information):**
 - OS: Mac/Linux
 - CPU architecture: arm (M3)
 - Browser
 - Version 

**Additional context**

**Comment by mdanish98** [comment]
Hi @gerberm-at-msg ,

Thanks for pointing out this issue, we will provide this fix soon.

**Comment by mateusmolina-iese** [comment]
Hi @gerberm-at-msg,

the image used in the build stage was not arm64 compatible. I created a pull request with a fix (https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/397). I tested it under docker platform emulation and it built successfully. 

Could you please check out the PR's branch and test if it's working on your machine? Thanks in advance.

**Comment by gerberm-at-msg** [comment]
Hi @mateusmolina-iese, 

I just tried to start it again. I still receive the following error message. 

I have tested additionally the manual set parameter (separate):
  
```
export DOCKER_DEFAULT_PLATFORM=linux/arm64/v8
export DOCKER_DEFAULT_PLATFORM=linux/arm64
unset DOCKER_DEFAULT_PLATFORM
```

```
! aas-discovery The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                   0.0s 
 ! sm-registry The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                     0.0s 
 ! aas-registry The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                    0.0s 
 ! aas-env The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested        
```

**Comment by mateusmolina-iese** [comment]
The snapshot images aren't currently available for arm64. Can you please change the tag of the services you added to the docker-compose using SNAPSHOT to the latest milestone (2.0.0-milestone-03.1)?

**Comment by gerberm-at-msg** [comment]
Hi @mateusmolina-iese, 

thank you. Now all docker start except of the basyx-dashboard-api (see at the bottom since it less relevant). 

After starting the environment crashes with the following error message
```
Loaded property file: file:application.properties
Loaded property file: jar:nested:/application/basyxExecutable.jar/!BOOT-INF/classes/!/application.properties
  ____           _____              
 |  _ \         / ____|             
 | |_) |  __ _ | (___   _   _ __  __
 |  _ <  / _` | \___ \ | | | |\ \/ /
 | |_) || (_| | ____) || |_| | >  < 
 |____/  \__,_||_____/  \__, |/_/\_\
======================== __/ |======      
AAS Environment         |___/                  
2.0.0-PREVIEW

2024-08-23T07:45:36.555Z  INFO 1 --- [AAS Environment] [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Starting AasEnvironmentComponent v2.0.0-milestone-03.1 using Java 17.0.12 with PID 1 (/application/basyxExecutable.jar started by nobody in /application)
2024-08-23T07:45:36.560Z  INFO 1 --- [AAS Environment] [           main] o.e.d.b.a.c.AasEnvironmentComponent      : No active profile set, falling back to 1 default profile: "default"
2024-08-23T07:45:38.067Z  INFO 1 --- [AAS Environment] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2024-08-23T07:45:38.076Z  INFO 1 --- [AAS Environment] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 6 ms. Found 0 MongoDB repository interfaces.
2024-08-23T07:45:38.117Z  INFO 1 --- [AAS Environment] [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2024-08-23T07:45:38.124Z  INFO 1 --- [AAS Environment] [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2024-08-23T07:45:38.452Z  INFO 1 --- [AAS Environment] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8081 (http)
2024-08-23T07:45:38.459Z  INFO 1 --- [AAS Environment] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-08-23T07:45:38.459Z  INFO 1 --- [AAS Environment] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.26]
2024-08-23T07:45:38.478Z  INFO 1 --- [AAS Environment] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-08-23T07:45:38.479Z  INFO 1 --- [AAS Environment] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1776 ms
2024-08-23T07:45:38.615Z  INFO 1 --- [AAS Environment] [           main] o.e.d.b.a.c.AasEnvironmentFeaturePrinter : -------------------- Aas Environment Features: --------------------
2024-08-23T07:45:38.615Z  INFO 1 --- [AAS Environment] [           main] o.e.d.b.a.c.AasEnvironmentFeaturePrinter : ----------------------------------------------------------------- 
2024-08-23T07:45:38.767Z  INFO 1 --- [AAS Environment] [           main] org.mongodb.driver.client                : MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync|spring-boot", "version": "5.0.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "aarch64", "version": "6.1.0-23-arm64"}, "platform": "Java/Amazon.com Inc./17.0.12+7-LTS", "env": {"container": {"runtime": "docker"}}} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName='mongoAdmin', source='admin', password=<hidden>, mechanismProperties=<hidden>}, transportSettings=null, commandListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener@2f471037], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@1d1cfe4, com.mongodb.Jep395RecordCodecProvider@ba562e0, com.mongodb.KotlinCodecProvider@5a51336a]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[mongo:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='15 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener@4d8056bf], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=JAVA_LEGACY, serverApi=null, autoEncryptionSettings=null, dnsClient=null, inetAddressResolver=null, contextProvider=null}
2024-08-23T07:45:38.769Z  INFO 1 --- [AAS Environment] [l'}-mongo:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=mongo:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=27115782}
2024-08-23T07:45:40.370Z  INFO 1 --- [AAS Environment] [           main] a.p.AasEnvironmentPreconfigurationLoader : Scanning for preconfigured AAS Environments
2024-08-23T07:45:40.375Z  INFO 1 --- [AAS Environment] [           main] a.p.AasEnvironmentPreconfigurationLoader : Found 2 preconfigured AAS environments
2024-08-23T07:45:40.376Z  INFO 1 --- [AAS Environment] [           main] a.p.AasEnvironmentPreconfigurationLoader : Loading AAS Environment (0/2) from file 'test_demo_full_example.xml'
2024-08-23T07:45:41.068Z  INFO 1 --- [AAS Environment] [           main] a.f.r.i.RegistryIntegrationAasRepository : Shell 'https://acplt.org/Test_AssetAdministrationShell' has been automatically linked with the Registry
2024-08-23T07:45:41.069Z  INFO 1 --- [AAS Environment] [           main] o.e.d.b.a.base.DefaultAASEnvironment     : Uploading shell https://acplt.org/Test_AssetAdministrationShell was successful!
2024-08-23T07:45:41.089Z  INFO 1 --- [AAS Environment] [           main] a.f.r.i.RegistryIntegrationAasRepository : Shell 'https://acplt.org/Test_AssetAdministrationShell_Mandatory' has been automatically linked with the Registry
2024-08-23T07:45:41.089Z  INFO 1 --- [AAS Environment] [           main] o.e.d.b.a.base.DefaultAASEnvironment     : Uploading shell https://acplt.org/Test_AssetAdministrationShell_Mandatory was successful!
2024-08-23T07:45:41.113Z  INFO 1 --- [AAS Environment] [           main] a.f.r.i.RegistryIntegrationAasRepository : Shell 'https://acplt.org/Test_AssetAdministrationShell2_Mandatory' has been automatically linked with the Registry
2024-08-23T07:45:41.113Z  INFO 1 --- [AAS Environment] [           main] o.e.d.b.a.base.DefaultAASEnvironment     : Uploading shell https://acplt.org/Test_AssetAdministrationShell2_Mandatory was successful!
2024-08-23T07:45:41.136Z  INFO 1 --- [AAS Environment] [           main] a.f.r.i.RegistryIntegrationAasRepository : Shell 'https://acplt.org/Test_AssetAdministrationShell_Missing' has been automatically linked with the Registry
2024-08-23T07:45:41.136Z  INFO 1 --- [AAS Environment] [           main] o.e.d.b.a.base.DefaultAASEnvironment     : Uploading shell https://acplt.org/Test_AssetAdministrationShell_Missing was successful!
2024-08-23T07:45:41.216Z  WARN 1 --- [AAS Environment] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:nested:/application/basyxExecutable.jar/!BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: Unable to link the element with id 'http://acplt.org/Submodels/Assets/TestAsset/Identification' with the Registry.
2024-08-23T07:45:41.220Z  WARN 1 --- [AAS Environment] [           main] o.s.b.f.support.DisposableBeanAdapter    : Invocation of close method failed on bean with name 'mqttClient': Client is connected (32100)
2024-08-23T07:45:41.227Z  INFO 1 --- [AAS Environment] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-08-23T07:45:41.246Z  INFO 1 --- [AAS Environment] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-08-23T07:45:41.260Z ERROR 1 --- [AAS Environment] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:nested:/application/basyxExecutable.jar/!BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: Unable to link the element with id 'http://acplt.org/Submodels/Assets/TestAsset/Identification' with the Registry.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1806) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971) ~[spring-context-6.1.11.jar!/:6.1.11]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.11.jar!/:6.1.11]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.2.jar!/:3.3.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.2.jar!/:3.3.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.2.jar!/:3.3.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.2.jar!/:3.3.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.2.jar!/:3.3.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.2.jar!/:3.3.2]
        at org.eclipse.digitaltwin.basyx.aasenvironment.component.AasEnvironmentComponent.main(AasEnvironmentComponent.java:42) ~[!/:2.0.0-milestone-03.1]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[basyxExecutable.jar:2.0.0-milestone-03.1]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[basyxExecutable.jar:2.0.0-milestone-03.1]
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[basyxExecutable.jar:2.0.0-milestone-03.1]
Caused by: org.eclipse.digitaltwin.basyx.core.exceptions.RepositoryRegistryLinkException: Unable to link the element with id 'http://acplt.org/Submodels/Assets/TestAsset/Identification' with the Registry.
        at org.eclipse.digitaltwin.basyx.submodelrepository.feature.registry.integration.RegistryIntegrationSubmodelRepository.integrateSubmodelWithRegistry(RegistryIntegrationSubmodelRepository.java:180) ~[basyx.submodelrepository-feature-registry-integration-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.submodelrepository.feature.registry.integration.RegistryIntegrationSubmodelRepository.createSubmodel(RegistryIntegrationSubmodelRepository.java:90) ~[basyx.submodelrepository-feature-registry-integration-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.submodelrepository.feature.operation.delegation.OperationDelegationSubmodelRepository.createSubmodel(OperationDelegationSubmodelRepository.java:81) ~[basyx.submodelrepository-feature-operation-delegation-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.environmentloader.IdentifiableUploader$DelegatingIdentifiableRepository.create(IdentifiableUploader.java:158) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.environmentloader.IdentifiableUploader.create(IdentifiableUploader.java:94) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.environmentloader.IdentifiableUploader.upload(IdentifiableUploader.java:55) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.base.DefaultAASEnvironment.createSubmodelsOnRepository(DefaultAASEnvironment.java:238) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.base.DefaultAASEnvironment.createSubmodelsOnRepositoryFromEnvironment(DefaultAASEnvironment.java:143) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.base.DefaultAASEnvironment.loadEnvironment(DefaultAASEnvironment.java:126) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.loadPreconfiguredEnvironments(AasEnvironmentPreconfigurationLoader.java:91) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.loadPreconfiguredEnvironment(PreconfigurationLoaderInitializer.java:68) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.afterPropertiesSet(PreconfigurationLoaderInitializer.java:60) ~[basyx.aasenvironment-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-6.1.11.jar!/:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802) ~[spring-beans-6.1.11.jar!/:6.1.11]
        ... 23 common frames omitted
Caused by: org.eclipse.digitaltwin.basyx.submodelregistry.client.ApiException: java.net.ConnectException
        at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.postSubmodelDescriptorWithHttpInfo(SubmodelRegistryApi.java:563) ~[basyx.submodelregistry-client-native-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.postSubmodelDescriptor(SubmodelRegistryApi.java:531) ~[basyx.submodelregistry-client-native-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        at org.eclipse.digitaltwin.basyx.submodelrepository.feature.registry.integration.RegistryIntegrationSubmodelRepository.integrateSubmodelWithRegistry(RegistryIntegrationSubmodelRepository.java:176) ~[basyx.submodelrepository-feature-registry-integration-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        ... 36 common frames omitted
Caused by: java.net.ConnectException: null
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:573) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:na]
        at org.eclipse.digitaltwin.basyx.submodelregistry.client.api.SubmodelRegistryApi.postSubmodelDescriptorWithHttpInfo(SubmodelRegistryApi.java:545) ~[basyx.submodelregistry-client-native-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
        ... 38 common frames omitted
Caused by: java.net.ConnectException: null
        at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1055) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Http1Exchange.java:239) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Exchange.java:472) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.Exchange.checkFor407(Exchange.java:404) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$10(Exchange.java:476) ~[java.net.http:na]
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340) ~[na:na]
        at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:476) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:380) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:372) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:408) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:449) ~[java.net.http:na]
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340) ~[na:na]
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:439) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:341) ~[java.net.http:na]
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[na:na]
        at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157) ~[java.net.http:na]
        at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2673) ~[na:na]
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:294) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:654) ~[java.net.http:na]
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:552) ~[java.net.http:na]
        ... 40 common frames omitted
Caused by: java.nio.channels.UnresolvedAddressException: null
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149) ~[na:na]
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[na:na]
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183) ~[java.net.http:na]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569) ~[na:na]
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185) ~[java.net.http:na]
        ... 65 common frames omitted
```



Regarding the warning of the basyx-dashboard-api
Here I still use the image: aaronzi/basyx-dashboard-api:SNAPSHOT_02

```
 ✔ Container aas-env                                                                                                                                            Created                                           0.0s 
 ! dashboard-api The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                   0.0s
```

**Comment by mateusmolina-iese** [comment]
There seems to be an issue with how the registry integration feature was configured. Can you please attach a zipped, reproducible example of your compose and configuration files? 

Regarding the aaronzi/basyx-dashboard-api image, it does not seem to be available for ARM64. @aaronzi, is this the case?

**Comment by gerberm-at-msg** [comment]
Thank you for taking the time looking into it. It is basically the example from https://basyx.org/get-started with logos, colour etc. Additionally, I have adjusted the IP-Address from localhost to a private network

[msgSetup.zip](https://github.com/user-attachments/files/16725816/msgSetup.zip)

**Comment by mateusmolina-iese** [comment]
There's a typo in your aas-env config:
```diff
# basyx/aas-env.properties
 basyx.cors.allowed-origins=*
 basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
 basyx.aasrepository.feature.registryintegration=http://192.168.178.76:8082
-basyx.submodelrepository.feature.registryintegration=http://192.1678.178.76:8083
+basyx.submodelrepository.feature.registryintegration=http://192.168.178.76:8083
 basyx.externalurl=http://192.168.178.76:8081
 ```

**Comment by gerberm-at-msg** [comment]
Oh thanks. Thats on me... 
![image](https://github.com/user-attachments/assets/f90651f8-04f8-43e8-8ad0-30d42f9f7d5e)

**Comment by gerberm-at-msg** [comment]
@aaronzi: The IP was independent from the question:

Regarding the aaronzi/basyx-dashboard-api image, it does not seem to be available for ARM64. @aaronzi, is this the case?
If there is no ARM64, is it planned to provide it at some point?
Cheers

**Comment by aaronzi** [comment]
Sorry, I reopened the issue again. Could you please open a new ticket if it does not fit to the original ticket title. If you still have issues with keycloak, please tell us so. Otherwise please close this one and we discuss the other topic in the new issue.

Best Regards, Aaron

**Comment by gerberm-at-msg** [comment]
I will open a new ticket for the basyx-dashboard-api with ARM64
Anyway we can close the ticket since the original issue was resolved, but the entire infrastructure is still not working when I activate rbac

Thank you!
Cheers Michael
