### ISSUE TITLE
[BUG] SubmodelElementRepository: Integer Value For Property Can't Be Used For Patching

### ISSUE THREAD

**Issue by geso02** [eclipse-basyx/basyx-java-server-sdk#403]
**Describe the bug**

My submodel repository contains a submodel with one property. I now try to patch the property using the value-only representation. The property representation could be a number, string or boolean value according to the [OpenApi-Definition](https://app.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.2#/components/schemas/PropertyValue). The property value is of type integer, so I expect that I could post an integer value, but only posting a string value works.

**To Reproduce**
1. Set up a submodel repository.
2. Post the submodel:
``` bash
  curl -X POST http://localhost:8081/submodels -H "Content-Type: application/json" -v -d '{
    "modelType": "Submodel",
    "kind": "Instance",
    "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
    "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
    "submodelElements": [{
            "modelType": "Property",
            "value": "12",
            "valueType": "xs:integer",
            "idShort": "prop"
        }
    ]
}'
```
3.  Perform a patch:
``` bash
 curl -X PATCH http://localhost:8081/submodels/aHR0cDovL3NtLnR3aW5maWNpZW50LmRlL1RlY2huaWNhbERhdGEvaGVhdGVyLWRlZmluaXRpb24vT3B0aW1hX1BsdXNfNDA=/submodel-elements/prop/\$value \
-H "Content-Type: application/json" \
-d '18'
``` 
4. Status Code is 500, so check out the error on server-side:
```
org.eclipse.digitaltwin.basyx.deserialization.exception.SubmodelElementValueDeserializationException: The provided SubmodelElementValue JSON is not as defined in the Dot AAS Part 2
	at org.eclipse.digitaltwin.basyx.deserialization.factory.SubmodelElementValueDeserializationFactory.create(SubmodelElementValueDeserializationFactory.java:99) ~[basyx.submodelservice-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
	at org.eclipse.digitaltwin.basyx.deserialization.SubmodelElementValueJsonDeserializer.deserialize(SubmodelElementValueJsonDeserializer.java:56) ~[basyx.submodelservice-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
	at org.eclipse.digitaltwin.basyx.deserialization.SubmodelElementValueJsonDeserializer.deserialize(SubmodelElementValueJsonDeserializer.java:46) ~[basyx.submodelservice-core-2.0.0-milestone-03.1.jar!/:2.0.0-milestone-03.1]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342) ~[jackson-databind-2.17.2.jar!/:2.17.2]
```
**Expected behavior**

Should  work for integer as it does for string (Jackson deserialization problem)

**BaSyx (please complete the following information):**
- BaSyx Version [ v2.0]
- BaSyx SDK [Java]
- AAS Version [ DotAAS V3]

**System (please complete the following information):**
 - OS: Windows
 - CPU architecture: x86

**Comment by aaronzi** [comment]
Thank you for reporting this. This seems like a duplicate of #384 but we will check this again to verify
